### ISSUE TITLE
NPM dependency warning when using React 16

### ISSUE THREAD

**Issue by UselessPickles** [ag-grid/ag-grid-react#100]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the latest versions of ag-grid-react (13.30) and react/react-dom (16.0.0), "npm install" reports the following warnings:

npm WARN ag-grid-react@13.3.0 requires a peer of react@^15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ag-grid-react@13.3.0 requires a peer of react-dom@^15.5.0 but none is installed. You must install peer dependencies yourself.

**Expected behavior**
I expect that ag-grid 13.30 should support React 16, such that React 16.0.0 satisfies its npm requirements. I expect there to be no npm warnings.

**Minimal reproduction of the problem with instructions**
In any project using ag-grid-react, update to ag-grid-react 13.30, react 16.0.0, and react-dom 16.0.0. Run "npm install" and observe the warning.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Mac OS X El Capitan
* **ag-grid-react version:** 13.3.0

* **ag-Grid/ag-Grid-Enterprise version:** 13.3.1

* **React version:** 16.0.0

* **Browser:** Irrelevant

* **Language:** Irrelevant

**Comment by ajkaushik** [comment]
We have the same issue. Is AgGrid React compatible with React v16?

**Comment by UselessPickles** [comment]
Release notes for 13.3.0 claim support for React 16: https://github.com/ag-grid/ag-grid-react/releases/tag/13.3.0

> AG-851: Added support for React 16

**Comment by seanlandsman** [comment]
13.3.0 does indeed support react 16 - its just the package.json in ag-grid-react that needs to be updated.

Your app should work fine with 13.3.0 and react 16 - you can ignore this warning.

A PR by @douglasduteil will fix this. Its been merged and will be available in our next release
