### ISSUE TITLE
incorrect peer dependency

### ISSUE THREAD

**Issue by dadamssg** [ag-grid/ag-grid-react#102]
I _believe_ `react-dom-factories` should be in "dependencies" rather than "peerDependencies". I just installed ag-grid and ag-grid-react and attempted to use it and was hit with this error. 

![image](https://user-images.githubusercontent.com/881986/32381308-60fc2c9c-c080-11e7-93a6-c1aeb0c0a482.png)

I was able to solve the error by downloading the package easily enough. However, it is my understanding that peer dependencies should only contain packages that are guaranteed to exist in the host project.

**Comment by seanlandsman** [comment]
Peer dependencies are dependencies that are expected in the hosting application - if the hosting application does not have them then the library in question cannot function.

In this case ag-grid-react expects react-dom-factories to be present by the hosting application.  The same applies for ag-grid, react and react-dom.

**Comment by dadamssg** [comment]
Why is react-dom-factories expected to be present in the hosting application? As far as I can tell, that's a pretty low level utility package that I only know about because I got an error from ag-grid-react. 

ag-grid-react is plugin to react/react-dom and ag-grid. It makes sense that those are expected in the host application. ag-grid-react is not a plugin to react-dom-factories. It just happens to depend on it to do some low level dom manipulation. 

I think the developer experience would be improve if react-dom-factories was moved to be a hard dependency.

**Comment by josgraha** [comment]
@seanlandsman I agree with @dadamssg here in the only place you are using this is
https://github.com/ag-grid/ag-grid-react/blob/f56ce21dbf82dc286015bd43a9b6f5da3788fce3/src/agGridReact.ts#L29-L34
please consider 
```js
React.createElement("div", { style: this.createStyleForDiv(), ref: e =>_this.eGridDiv = e } });
```
as an alternative or move `react-dom-factories` to a hard dependency
