### ISSUE TITLE
Grid does not care about updated props, only takes their first(on first render) representation.

### ISSUE THREAD

**Issue by martlaboloa** [ag-grid/ag-grid-react#104]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Grid does not care about updated props, only takes their first(on first render) representation, Well at least *getContextMenuItems* prop acts that way.

**Expected behavior**

Say, I gave *getContextMenuItems* prop which had only one item in it, and then something changed in redux and I happen to want to add another item in context menu, for that I would make *getContextMenuItems* dependent on redux store and I would expect grid to use this renewed version of *getContextMenuItems*. 

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/DP7CnPyUYOb5zZ5Z3AXs?p=preview
Instructions: so I took redux-example(https://www.ag-grid.com/example-react-redux/), and I changed GridComponent.jsx(mostly it's render method). originally it happens so that that render method runs twice, so I have variable(cnt) outside of GridComponent class, which equal zero initially and I increase it on every render, this way I know which render it is, inside of render method, aaaand on first render I am giving initial representation of *getContextMenuItems* to grid, and on every consecutive render I'm giving different from first one(in this case only two render happens).  You can see that grid most definitely recieves renewed version of *getContextMenuItems* but it does not care, when you make context menu appear, still first one shows.

**What is the motivation / use case for changing the behavior?**

I get that you(agGrid team) probably first wrote grid on vanilla javascript, and thying to make it agnostic, for react, angular, aurelia and so on, and its hard to keep up with everything, but one of the fundamental idea of react is that you listen to prop changes and change you component accordingly, maybe not always, but in *getContextMenuItems*'s case its definitely needed.

I happen to have experience in dealing with similar issue, when component's(in this case grid's) state is somehow dependent on it's props, and I was not changing state according to renewed props, was not using *componentWillReceiveProps* at all, and I think that in you case that very higher level bug, like bug in design probably, so I want to know if I should expect it to be fixed any time soon, like approximately when will it be fixed? week, month, year? If ever ...?

Here is my example why I needed grid to listen to *getContextMenuItems* prop changes:
I am using gridAPI in *getContextMenuItems*, given how you cant use gridAPI until onGridReady executes(and first render is obviously happed when it does), you definitely want grid to take renewed *getContextMenuItems*, because when onGridReady executes and gives me apis I update store, telling to it that i have api's now or something like that, and then using that information in *getContextMenuItems*. 

**Please tell us about your environment:**

* **ag-grid-react version:** 13.3.0

* **ag-Grid/ag-Grid-Enterprise version:** 13.3.1

* **React version:** 16.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

   I am using Chrome 60.0.3112.78, but this issue is not browser specific(probably)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
javaScript, es6

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by tim-lukacik** [comment]
I was able to get around this limitation this using @brettinternet's key solution on #77
