### ISSUE TITLE
Style documentation not clear

### ISSUE THREAD

**Issue by maasencioh** [ag-grid/ag-grid-react#105]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Behavior**
The style example is outdated with [webpack loaders](https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules) in the documentation and missing a note about the need of fixing a container with a given height (_this behaviour also might be changed in the future for a better user experience_), as pointed out in:

* https://stackoverflow.com/questions/39608309/ag-grid-react-does-not-render-properly
* https://stackoverflow.com/questions/40835566/ag-grid-react-table-not-displaying

This two elements could save a lot of time for new clients if specify in the [themes documentation](https://www.ag-grid.com/javascript-grid-styling/#gsc.tab=0) and in the [detailed documentation](https://www.ag-grid.com/react-more-details/#gsc.tab=0).

There's also a difference in the *Loading CSS* documentation of the detailed documentation, is that there's not a `ag-grid-root` project, so it should be:

```js
import 'ag-grid/dist/styles/ag-grid.css';
import 'ag-grid/dist/styles/theme-fresh.css';
```

**Environment**

* **ag-grid-react version:** 14.2.0

* **webpack version:** 3.8.1

* **React version:** 16.1.1

* **Language:** ES6/7

**Comment by petyosi** [comment]
Hey, 

can you please post a link to the style example you refer to? We have several of those.

**Comment by maasencioh** [comment]
@petyosi you are right, this is the file I looked at https://github.com/ag-grid/ag-grid-react-example/blob/master/config/webpack.config.examples.js
