### ISSUE TITLE
Multiple spaces in row data are not being reflected in a cell.

### ISSUE THREAD

**Issue by VyvIT** [ag-grid/ag-grid-react#106]
**I'm submitting a
```
[x] bug report
```

**Current behavior**
Whitespace in between the words is being trimmed inside the cells.

**Expected behavior**
Expect to see all the whitespaces provided by row data.

**Minimal reproduction of the problem with instructions**
Plunker: https://plnkr.co/edit/W3DtzpjsRgd1SVTVQV2L?p=preview
Note in DynamicComponentsExample line 43 row  data is generated with multiple spaces in a 'row' field with `Row <multiple spaces> - <multiple spaces> ${i}`, but cells are rendered as 'Row - 0', 'Row - 1', etc.

* **ag-grid-react version:** 14.2.0
* **Browser:** [all ]
* **Language:** [ES6/7 | ES5]

**Comment by StevenMassaro** [comment]
@VyvIT Was this resolved? This issue still exists in ag-grid version: 16.0.1.

**Comment by smver** [comment]
@VyvIT Was this resolved? This issue still exists in ag-grid version: 16.0.1.

**Comment by smver** [comment]
Thanks @VyvIT, I got it figured out.

In our situation, we had our CSS set 
```
ag-cell:{
   white-space: nowrap;
}
```
which caused the white space characters to be collapsed. Changing it to `pre-wrap` solved our issue.
