### ISSUE TITLE
AgGridColumnProps extends both ColDef, ColGroupDef instaid of being a union type

### ISSUE THREAD

**Issue by evestraw** [ag-grid/ag-grid-react#107]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
AgGridColumnProps extends both ColDef, ColGroupDef
the compiler shows errors when the props are not both a colDef and ColGroup def
**Expected behavior**

the compiler shouldnt throw errors
**Minimal reproduction of the problem with instructions**

make an react grid project in typescript. and make a column without children

**What is the motivation / use case for changing the behavior?**

no behaviour will be changed. but compile errors wil be removed
**Please tell us about your environment:**

windows 10, visual studio code npm, 
* **ag-grid-react version:14.2.0.

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **React version:** 16.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [ TypeScript 2.6.1]

suggested resolution 
make AgGridColumnProps a union type instaid of an interface
```
export type AgGridColumnProps = ColDef | ColGroupDef
```

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by deathwebo** [comment]
Hi @evestraw is there a workaround for this issue ? I'm currently converting a project to Typescript and I've just found about this.

Thanks!

**Comment by evestraw** [comment]
Not using jsx columns and put it in options instead the columns can't
change after initial render anyway Wich was one of my requirements
