### ISSUE TITLE
cellRenderer not called when row data changes (ag-grid 16)

### ISSUE THREAD

**Issue by shivpatel** [ag-grid/ag-grid-react#110]
Using ag-grid (16.0.1) and ag-grid-react (16.0.0).

Noticing that `cellRendererFramework` always work correctly. However, `cellRenderer` is only called when the # of rows in my dataset changes. If I manipulate any value on an existing row, cellRender is not called for any of the columns.

Anyone else noticing this issue?

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
