### ISSUE TITLE
MouseEvent undefined during SSR

### ISSUE THREAD

**Issue by justan0therdave** [ag-grid/ag-grid-react#111]
I'm submitting a bug report `ReferenceError: MouseEvent is not defined at ./node_modules/ag-grid/dist/lib/widgets/agCheckbox.js:173:42`when using ag-grid for SSR react.

ag-grid v.16.0.1

as reported on  [ag-grid/ag-grid/issues/2187](https://github.com/ag-grid/ag-grid/issues/2187)

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
