### ISSUE TITLE
CellRendererFramework does not work properly with null values

### ISSUE THREAD

**Issue by fauricioRojas** [ag-grid/ag-grid-react#112]
**I'm submitting a...** 
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In my grid the first column must contains expand & collapse functionality, for that reason I added to its columnDef the following code:
```
{
  cellRenderer: 'group',
  cellRendererParams = {
    innerRendererFramework: MyCustomCellRenderer
  },
  cellRendererFramework: null
}
```
...the other columnDefs have the following code:
```
{
  cellRenderer: null,
  cellRendererParams: null,
  cellRendererFramework: MyCustomCellRenderer
}
```
Exactly in the first column when a cell has a `null` value, this cell is not been rendered but it only happens for the first column, the rest of the columns with `null` values in its cells are renderer properly.

**Expected behavior**

Cells with `null` values are rendering.

**Please tell us about your environment:**

* **ag-grid-react version:** 13.3.0

* **ag-Grid/ag-Grid-Enterprise version:** Not used

* **React version:** 15.4.0

* **Browser:** all

* **Language:** ES6

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
