### ISSUE TITLE
RowData is not able to store a property named 'style' and render it in the cellRendererFramework due to inability of using areEquivalent_Eq_91_2_34 on frozen (not extensible) props

### ISSUE THREAD

**Issue by HydraOrc** [ag-grid/ag-grid-react#115]
**I'm submitting a ...**
```
[ x ] bug report
```

**Current behavior**
Error: Uncaught (in promise) TypeError: Cannot add property areEquivalent_Eq_91_2_34, object is not extensible #81 

**Expected behavior**
No error or at least noticeable warning in the documentation

**Minimal reproduction of the problem with instructions**
If rowData has a property called 'style' and it is passed to the cellRendererFramework, which uses it as a style property on a div:

```
rowData: [
    {
        name: {
            style: {
                backgroundColor: 'red'
            }
        }
    }
]
```

`<div style={style} />`

In react-dom's function setInitialDOMProperties, if you name your property as 'style':

```
if (propKey === STYLE) {
  {
    if (nextProp) {
      // Freeze the next style object so that we can assume it won't be
      // mutated. We have already warned for this in the past.
      Object.freeze(nextProp);
    }
  }
}
```

A style property is being used on our div so it freezes this object for future extensions.

To solve this problem I had to change the property name to 'cellStyle' AND pass it to the div via clone:

`<div style={clone(cellStyle)} />`

**What is the motivation / use case for changing the behavior?**
This package's behavior conflicts with the core React code

* **ag-grid-react version:** 13.3.0

* **ag-Grid/ag-Grid-Enterprise version:** 13.0.0

* **React version:** 16.2.0

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
