### ISSUE TITLE
Problem with data insert in epic

### ISSUE THREAD

**Issue by sudohq** [ag-grid/ag-grid-react#116]
**I'm submitting a**
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Using InfiniteScroll type of grid, and when we add any data - its don't render in our grid.

**Expected behavior**
According to the issue, we need to render our data inside the grid.

**Minimal reproduction of the problem with instructions**
So, we have an AgGridReact component with  `rowModelType={'infinite'}` and also we create datasource with 

`
datasource={{
            rowCount: null,
            getRows: this.getRows
 }}
`

where in `getRows` method we use  `params.successCallback` for data insertion in our epic according to specific data's  structure. And that's it. Nothing rendered on out grid.

`
 initialAction.successCb(items.data.items, items.data.items.length);
`

**What is the motivation / use case for changing the behavior?**
For normal lib functional.

**Please tell us about your environment:**
MacOS Sierra, atom/webstorm/yarn/webpack-dev-server

* **ag-grid-react version:** 17.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 17.0.0

* **React version:** 16.0.1

* **Browser:** [all]

* **Language:** [TypeScript 2.6.2]

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
