### ISSUE TITLE
TypeScript build error (type issues) with ag-grid-react 

### ISSUE THREAD

**Issue by Mario-Eis** [ag-grid/ag-grid-react#118]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

containerStyle (as discussed in https://github.com/ag-grid/ag-grid-react/issues/29) is missing in the types. Resulting in:

`TS2339: Property 'containerStyle' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Readonly<{ children?: ReactNode; }>...'.`

and

```
TS2322: Type '{ headerName: string; field: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridColumn> & Readonly<{ children?: ReactNode; }...'.
  Type '{ headerName: string; field: string; }' is not assignable to type 'Readonly<AgGridColumnProps>'.
    Property 'children' is missing in type '{ headerName: string; field: string; }'.
```
also discussed in https://github.com/ag-grid/ag-grid/issues/2255

**Expected behavior**

No build issues with typescript

**Minimal reproduction of the problem with instructions**

Just do the following basic ag-grid setup in typescript
```
    <div className={"ag-theme-balham"}>
        <AgGridReact containerStyle={{height: null, flexGrow: 1}} rowData={...} enableColResize>
            <AgGridColumn headerName="header1" field="..."/>
        </AgGridReact>
    </div>
```

**What is the motivation / use case for changing the behavior?**

To be able to build with typescript.

**Please tell us about your environment:**

* **ag-grid-react version:** ^17.0.0

* **ag-Grid/ag-Grid-Enterprise version:** ^17.0.0

* **React version:** 16.3

* **Language:** TypeScript 2.8.1

**Comment by seanlandsman** [comment]
Closing as covered by https://github.com/ag-grid/ag-grid/issues/2255

**Comment by rrmarriott** [comment]
@seanlandsman - was this fixed? I don't see `containerStyle` in the type definitions here https://github.com/ag-grid/ag-grid/blob/master/packages/ag-grid-react/lib/agGridReact.d.ts
