### ISSUE TITLE
Row selection pains

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid-react#119]
So much pain is caused by not having row selection being controlled by props. This means we have to set the selected row node in a grid ready event or lifecycle method, compare props, find and programmatically select a row node, guard against causing an infinite loop (because a selection event happens for a deselection after the new node is selected for some reason), hope selection isn't lost between updates etc. It's nasty and not the "react"/modern approach for controlled components. Is there any plans to change this? e.g.

```js
<Grid
  getRowNodeId={data => data.id}
  selectedId={this.state.selectedId}
  onRowSelected={e => this.setState({ selectedId: event.node.id })
```

Similarly why would we want to programmatically do anything like show a loading overlay? It should be:

```js
<Grid
  isLoading={true}
```

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
