### ISSUE TITLE
The React method `unstable_renderSubtreeIntoContainer` will be removed soon. Will you stop using it before this happens?

### ISSUE THREAD

**Issue by sebinsua** [ag-grid/ag-grid-react#120]
Internally you are using [`unstable_renderSubtreeIntoContainer`](https://github.com/ag-grid/ag-grid-react/blob/5e38761c4b695c821f3062ceb206c66bf55274cd/src/agReactComponent.ts#L45-L48) to implement [React Cell Rendering](https://www.ag-grid.com/javascript-grid-cell-rendering-components/#react-cell-rendering).

In July 2017, [a GitHub issue about removing it](https://github.com/facebook/react/issues/10143#issuecomment-384767138) was created, and a few days ago a core React developer commented "It's time to deprecate it. Want to send a PR?".

I do not know whether it will be immediately removed in a next version, or whether it will start giving user's warnings whenever they use it, however it looks like removal is imminent and you should look into moving to [Portals](https://reactjs.org/docs/portals.html) or working out some other approach.

**Comment by jameswyse** [comment]
:+1:

I've been seeing the below error occasionally after upgrading to React 16.4. seems to occur during the `componentWillUnmount` phase when the component/ag-grid is destroyed.

<img width="974" alt="subtree" src="https://user-images.githubusercontent.com/1144357/40821061-cc78eb96-65a7-11e8-91e0-9c3a9b30ac0b.png">

**Comment by seanlandsman** [comment]
Thanks for reporting this.

We'll be looking at this for our next release - we've raised an internal item (AG-1905) for this which you can track at our pipeline here: https://www.ag-grid.com/ag-grid-pipeline/

Note: The issue may only appear in the pipeline immediately.

**Comment by seanlandsman** [comment]
@sebinsua @jameswyse 

I've release a beta release to resolve this - 18.1.3-beta.1

To enable it, set gridOptions.reactNext to true

If you're using redux you'll have a couple of extra steps too - let me know if you are

thanks
