### ISSUE TITLE
`deltaRowDataMode` prevents cell style updates

### ISSUE THREAD

**Issue by StephanieYHe** [ag-grid/ag-grid-react#121]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When `deltaRowDataMode={true}` and we change underlying data, the cellStyle does not update based on the changed data. However, if `deltaRowDataMode={false}` and we change the underlying data, cellStyle changes also take hold.

**Expected behavior**
When underlaying data changes, the cellStyles for the data apply, regardless of whether or not the `deltaRowDataMode` attribute is set.

**Minimal reproduction of the problem with instructions**

```
render() {
  return (
    <AgGridReact
      rowData={data}
      deltaRowDataMode={true}
    >
      <AgGridColumn
        colId="col_id"
        headerName="Column ID"
        valueGetter={{data} => data.id}
        cellStyle={{data} => cellStyle(data)}
      />
    </AgGridReact>
  );
}

function cellStyle(data) {
  if (data.clickable) {
    return {cursor: "pointer"};
  } else {
    return {};
  }
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-react version:** 2.0.X

```
ag-grid-react@^17.0.0:
  version "17.0.0"
  resolved "https://registry.yarnpkg.com/ag-grid-react/-/ag-grid-react-17.0.0.tgz#363d78b95b9be3bb2124284d2baf70056808f287"
  dependencies:
    prop-types "15.6.0"

```

* **ag-Grid/ag-Grid-Enterprise version:** 
```
ag-grid-enterprise@^17.0.0:
  version "17.0.0"
  resolved "https://registry.yarnpkg.com/ag-grid-enterprise/-/ag-grid-enterprise-17.0.0.tgz#760769c9400f6eb60213a06ca2c5fe91c92d9fd4"

ag-grid@^17.0.0:
  version "17.0.0"
  resolved "https://registry.yarnpkg.com/ag-grid/-/ag-grid-17.0.0.tgz#b8c82268c1785e04425a3149ca53cc526376029b"
```

* **React version:** 

```
react@^16.2.0, react@^16.3.0:
  version "16.3.0"
  resolved "https://registry.yarnpkg.com/react/-/react-16.3.0.tgz#fc5a01c68f91e9b38e92cf83f7b795ebdca8ddff"
  dependencies:
    fbjs "^0.8.16"
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
    prop-types "^15.6.0"
```

* **Browser:** Chrome 66.0.3359.139

* **Language:** ES6

**Comment by jwhitefield-hark** [comment]
I have found the same issue on an angular flavored project (although I suspect this info is redundant). 
As a short term measure I am redrawing the rows, its not ideal but better that than display incorrect view.

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid

**Comment by nabils** [comment]
Why was this closed? I am still able to reproduce it on 21.0.1 enterprise. I am using it with react and setting rowData via a prop each time my data set changes. I use deltaRowDataMode along with getRowNodeId to make sure the deltas are handled properly which works fine. Problem is my conditional styles (through cellStyle function are not applied when the data is updated). If I set deltaRowDataMode to false it works.

**Comment by jwhitefield-hark** [comment]
@nabils I think it was due to my inability to provide a reproducible example, unfortunately I just don't have the time to do this hopefully if you have a repeatable example you do.

**Comment by nabils** [comment]
@jwhitefield-hark Thanks for letting me know

@AG Grid team
I have tried calling refreshData() on rowDataUpdated and that does not work. Only thing that does work is redrawRows() which seems way too heavy for this.

Please can you confirm you are not able to reproduce this at all before I spend time putting together a sample? I am an enterprise user.
