### ISSUE TITLE
Cannot hide "No Rows To Show" overlay

### ISSUE THREAD

**Issue by jeghers** [ag-grid/ag-grid-react#124]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling hideOverlay does nothing.  I've tried calling it at different places in the component code and lifecycle, no change.

**Expected behavior**
We need some way to hide that overlay, or, even better, replace it with something of our own.  Preferably something more React-like, like setting a property, not calling a function.

**Minimal reproduction of the problem with instructions**
Create an empty grid in React and try to hide the overlay...

**What is the motivation / use case for changing the behavior?**
We really need to matccch some other UI code in visual style

**Please tell us about your environment:**
Windows and CentOS, running Node/Express

* **ag-grid-react version:**
    "ag-grid": "^16.0.1",
    "ag-grid-react": "^16.0.0",

* **React version:**
    "react": "16.3.2",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 67.0.3396.87

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6

**Comment by seanlandsman** [comment]
As per the readme, please provide a reproducible/runnable example.

If you can provide this and believe that this is still an issue, please raise a new issue here: https://github.com/ag-grid/ag-grid
