### ISSUE TITLE
AG Grid Not Unmounting properly after upgrading to React-16

### ISSUE THREAD

**Issue by HariAkunuri** [ag-grid/ag-grid-react#134]
Hello All,
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search Github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit the support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the component is being mounted in tabs, when you unmount it and try to remount it we are getting an error:
"Error: Expected subtree parent to be a mounted class component. This Error is likely caused due to a bug in React. Please file an issue."

**Expected behavior**
The component using the AG-Grid should be unmounted properly when changing the tabs.
 
**Minimal reproduction of the problem with instructions**
1. When a component containing AG-Grid is being used and mounted in Tabs
2. The component is not getting unmounted properly.
3. When you remount the same tab again, we are getting the error mentioned above. 

**What is the motivation/use case for changing the behavior?**
The component using AG-Grid should unmount properly when the tab is changed.

**Please tell us about your environment:**
Windows 10, Web-Storm, Node, NPM

* **ag-grid-react version:** 2.0.X
ag-grid-react: 19.0.0 (latest version)

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
ag-grid-enterprise: 19.0.0 (latest version)
ag-grid-community: 19.0.0 (latest version)

* **React version:** 2.0.X
react: 16.5.2
react-dom: 16.5.2

* **Browser:**
Chrome

* **Language:** 
ES6

**Comment by VasilyShelkov** [comment]
I am having a similiar issue but in different circumstances with the same error. I'm assuming this suggests that ag-grid-react does not support React 16 ?

![screenshot 2018-10-30 at 16 38 15](https://user-images.githubusercontent.com/7474810/47734472-4954cc80-dc62-11e8-969f-5e102182f71f.png)

**Comment by brendonco** [comment]
I'm getting the same error.

```
    "ag-grid": "18.0.1",
    "ag-grid-enterprise": "18.0.1",
    "ag-grid-react": "18.0.0",
"react": "16.2.0",
"react-dom": "16.2.0",
```

**Comment by seanlandsman** [comment]
Hi

React 16 is supported - please refer to the docs here for more information: https://www.ag-grid.com/react-more-details/#react-portals

Note that we've corrected a couple of issues around this area so the next version will be even better, fully supporting Portals and the new context API. The next release will be in early January

thanks

**Comment by paulspiteri** [comment]
I'm seeing this problem now when using a portal, with:

    "ag-grid-community": "^21.2.2",
    "ag-grid-enterprise": "^21.2.2",
    "react": "^16.10.2",

**Comment by omnibrain** [comment]
Yup, same for me. Exactly the same versions as @paulspiteri 

Any idea what's causing it?

**Comment by seanlandsman** [comment]
@omnibrain @paulspiteri  Can you try with ag-grid-react@22.0.0-beta.2 and let me know if this resolve the problem for you?

**Comment by omnibrain** [comment]
With ag-grid-react@22.0.0-beta.2 I coulnd't even compile my project anymore but with 22.0.0-beta.3 the errors are gone!
