### ISSUE TITLE
Functional components don't rerender when refresh cells is called

### ISSUE THREAD

**Issue by sachinshettigar** [ag-grid/ag-grid-react#139]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

When a functional component is passed as cell renderer for a column, it cell is not rerendered when refreshCells method is called on the grid.

**Current behavior**
    Columns are not rerendered when  datagrid refresh cells is called.

**Expected behavior**
   Columns must be rerendered when datagrid refresh cells is called.

**Minimal reproduction of the problem with instructions**
Plunker: 
https://plnkr.co/edit/qEPkrDAkQxEzaTQ8OpOi?p=preview
Steps: 
Square column is editable. so changing a value in this column should update Cube column values

I'm passing a functional component to the cellRendererFramework property of colDef
Eg: 
```
  {
          headerName: "Cube",
          field: "value",
          cellRendererFramework: CubeRenderer,
          colId: "cube",
          width: 150
        },
```

and i'm calling grid refresh cells method in onCellValueChanged method

```
onCellValueChange(params){
    console.log("onCell Value changed");
    params.api.refreshCells({force: true});
  //params.api.redrawRows();
  }

```
cubeRenderer is defined as below
```
const CubeRenderer = (params) => {
  const cube = params.value * params.value * params.value;
  console.log("Rerender cubes", cube);
  return (
    <span>{cube}</span>
  )
}
```

* **ag-grid-react version:** ag-grid-react@19.1.1

* **ag-Grid/ag-Grid-Enterprise version:** ag-grid@19.1.1

* **React version:** react@16.0.0',

**Comment by seanlandsman** [comment]
Hi

thanks for reporting this - this will be fixed in the next release
