### ISSUE TITLE
AG-grid not passing context to cell component in Redux V6 due to new Context API 

### ISSUE THREAD

**Issue by ji-meng** [ag-grid/ag-grid-react#142]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Redux V6 was released on Dec 5 2018 with some change on how the connect components access the store context (Please see the details in their [release note](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0) )

As a result, having a connected react component as cell render in AG grid no longer work with the latest Redux because Redux V6 no longer support accessing the store instance out of legacy context.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

A similar problem was reported in 2017 (https://github.com/ag-grid/ag-grid-react/issues/88). The way to reproduce the problem is the same as that issue, just change the redux to the latest version (V6.0.0 as of writing)  

**What is the motivation / use case for changing the behavior?**
latest Redux (V6) support the new Context API added in React 16.4. As a result it no longer support accessing the store instance out of legacy context.

**Please tell us about your environment:**
Ubuntu 18.04 in VM

* **ag-grid-react version:** 2.0.X
all
* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
all

* **React version:** 2.0.X
16.7.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by lilbumblebear** [comment]
I was having trouble with this too until I found this documentation:
https://www.ag-grid.com/react-more-details/#react-portals

All I had to do was:

1. Add `reactNext={true}` to my `<AgGridReact/>` component
2. On my connected component change
`connect(mapStateToProps)(ConnectedComponent);`
to
`connect(mapStateToProps,null,null,{ forwardRef: true })(ConnectedComponent);`

It took me a while to find that documentation, but works well once I made those changes!

**Comment by seanlandsman** [comment]
As @lilbumblebear says above, this is covered in our docs here https://www.ag-grid.com/react-more-details/#react-portals

thanks

**Comment by baleeds** [comment]
Is this going to be adjusted in later versions, because the current solution is very inconvenient?  

I am having three problems with the current solution:
1. I can't pass functional components as grid renderers, because they don't take refs.
2. I can't connect components inside of a renderer, only the renderer itself.  That sort of defeats the purpose of connect, which is to keep the store access local to each reusable component
3. Connecting is now more verbose and 'boilerplatey'.
