### ISSUE TITLE
feature request: allow Components to be specified in certain string-namespace fields so the React interface is more DRY

### ISSUE THREAD

**Issue by rob2d** [ag-grid/ag-grid-react#143]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

Hi, currently using this library as enterprise user for a project and am finding the API is pretty redundant. I am not sure if this has been brought up before, but some things a bit too out-of-the-way for React and also lead to unneeded performance considerations -- especially with newer devs or just people who want convenience of an intuitive React API with streamline perf by default in examples. There are a lot of props which are referencing another class redundantly whereas this should be unnecessary. Changing any component passed to AgGridReact could trigger a re-render anyhow, thus the whole concept of needing to namespace component mapping seems a little bit off.

You can see the problem example below.

**Minimal reproduction of the problem with instructions**

Lets look at `frameworkComponents` prop as an example. You need to provide not only a `frameworkComponents` namespace, but it has to have an object full of namespaces and key matching to components, and even in the doc we are creating a non-flat literal JSON in state for namespace `frameworkComponents`, and then also defining every single component. In React, these components can (and probably should) already be defined by a namespaced function/class as shown here:

```
// JSX snippet
<AgGrid 
     {...otherProps}
     frameworkComponents= {{
        customLoadingOverlay: 'customLoadingOverlay',
        customNoRowsOverlay: 'customNoRowsOverlay'
     }}
     customNoRowsOverlay={NoRowsOverlayComponent},
     customLoadingOverlay={LoadingOverlayComponent}
/>
```

A much more sane default which would not have perf implications would be allow to check for something other than a string specified so we can use a flat set of props without these nested objects with string namespaces. I am not sure internally how this links to `AgGrid` but another very easy  solution during render of the AgGridReact component would be to memoize a function in however AgGrid's interface is linked like the following:

```
function getFrameworkComponentProps(components) {
    const props = {
        frameworkComponents : {}
    };

    for(let [key, component] of Object.entries(components)) {
        props.frameworkComponents[key] = component;
        props[key] = key;
    }

    return props;
}


/**
 * frameworkComponent props
 */
const frameworkComponentProps = getFrameworkComponentProps({
    'noRowsOverlayComponent' : NoRowsToShow
});

// then you can use props in spread operator with
// { ... frameworkComponents }
```

**What is the motivation / use case for changing the behavior?**

The props interface could be much less redundant for most default real world cases without needing boilerplate or creating a custom-HOC/etc so inexperienced developers know that this is an anti-pattern to use as shown in docs.

[slightly OT as well in the React doc examples such as just throwing colDefs and other props which in default cases are just constants into the state]

**Please tell us about your environment:**

Windows 7/VSCode@latest/NPM5.X

* **ag-grid-react version:** 2.0.X

19.1.2
* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

18.1.X
* **React version:** 2.0.X

16.7.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
I'm not sure I understand what you're doing here:

`
// JSX snippet
<AgGrid 
     {...otherProps}
     frameworkComponents= {{
        customLoadingOverlay: 'customLoadingOverlay',
        customNoRowsOverlay: 'customNoRowsOverlay'
     }}
     customNoRowsOverlay={NoRowsOverlayComponent},
     customLoadingOverlay={LoadingOverlayComponent}
/>
`

This should look something like this:

`<AgGrid 
     {...otherProps}
     frameworkComponents= {{
        customLoadingOverlay: {NoRowsOverlayComponent},
        customNoRowsOverlay: {LoadingOverlayComponent}
     }}
     customNoRowsOverlay='customLoadingOverlay'
     customLoadingOverlay='customNoRowsOverlay'
/>`

or

`<AgGrid 
     {...otherProps}
     customNoRowsOverlayFramework={NoRowsOverlayComponent},
     customLoadingOverlayFramework= {LoadingOverlayComponent}
/>`

Registering components by name allows for a more flexible approach, but if you don't need/want this you can use the latter approach.
