### ISSUE TITLE
Custom cellRenderer using redux-connected component breaks with new versions of react-redux >= 6.x.x

### ISSUE THREAD

**Issue by Q-Man** [ag-grid/ag-grid-react#147]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using a custom cellRenderer which is rendering a react-redux >= 6.x.x connected component there's the following console error (still works with react-redux <= 5.1.1):

`Uncaught Invariant Violation: Could not find "store" in the context of "Connect(TestComponent)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(TestComponent) in connect options.`

There was a similar issue a while ago: https://github.com/ag-grid/ag-grid-react/issues/88

**Expected behavior**

The redux-connected component should be correctly rendered inside the custom cellRenderer.

**Minimal reproduction of the problem with instructions**

I created a demo for this bug:
https://github.com/Q-Man/ag-grid-cell-renderer-bug

This example breaks when using react-redux >= 6.x.x and works with react-redux <= 5.1.1

**What is the motivation / use case for changing the behavior?**

It should be possible to render redux-connected components inside custom cellRenderers

**Please tell us about your environment:**

Windows 10, IntelliJ IDEA, npm

* **ag-grid-react version:** 20.2.0

* **React version:** 16.8.6

* **Browser:** [all]

* **Language:** [all]

**Comment by Q-Man** [comment]
Update: Same behaviour with the latest 7.0.3 version of react-redux.

**Comment by gokulkrishh** [comment]
@Q-Man Yep. It works with react-redux <= 5.1.1 but not > 5.1.1. Is anyone looking into this issue ?

**Comment by ShonP** [comment]
also having kind of same issue with styled components theme context

**Comment by blacksteed232** [comment]
I don't know if this is related but I was trying to make `react-router` <Link> works in cellRendererFramework and by enabling `reactNext={true}` in <AgGridReact> it works for me.

See the [doc](!https://www.ag-grid.com/react-more-details/#react-16)
Some other people are talking about this [here](!https://github.com/ag-grid/ag-grid-react/issues/142)

**Comment by Q-Man** [comment]
`reactNext={true}` solved the problem, thank you.

I'm closing this bug now. 

It would be great if there could be a warning console output if someone is using react >= 16 without `reactNext={true}` set.

**Comment by lacksfish** [comment]
This drove me crazy today. Thanks @blacksteed232 for the great solution!

**Comment by seamus-quinn** [comment]
Thank you thank you @blacksteed232  for this.  Been trying to figure this out for a long time!
