### ISSUE TITLE
ag-grid-react does not work with ag-grid-enterprise

### ISSUE THREAD

**Issue by JeremyColton** [ag-grid/ag-grid-react#148]
I'm submitting a bug report

**Current behavior**
I follow the install instrucitons at https://www.ag-grid.com/react-getting-started/ but want to use the enterprise edition so I run:

`npm i --save ag-grid-enterprise ag-grid-react`

App installs but on running I get this error:

```
Failed to compile.

./node_modules/ag-grid-react/lib/agGridReact.js
Module not found: Can't resolve 'ag-grid-community' in 'C:\Workspace\react-apps\test-ag-grid\node_modules\ag-grid-react\lib'
```

**Expected behavior**
App compiles and runs

I looked inside the \node_modules\ag-grid-react\lib\reactComponent.js file and it says:
`var AgGrid = require("ag-grid-community");`

So the react abstraction of ag-grid requires the community edition and won't work with the enterprise edition?

OS: Windows 10
ag-grid-enterprise 20.2.0
ag-grid-react 20.2.0
react: 16.8.6

Browser:Chrome
Language:ES6

**Comment by dark-wind** [comment]
you may need install ag-grid-community by
```
npm i --save ag-grid-community
```

**Comment by JeremyColton** [comment]
Thanks, I had to install both versions for it to work with React. Documentation was not clear on this.
