### ISSUE TITLE
reactNext={true} causing my customFilter dialog invoking at random location. not at anchor element

### ISSUE THREAD

**Issue by vsn530** [ag-grid/ag-grid-react#166]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Before setting reactNext={true}, i can see the filter popup invoked at desired place, but after seting reactNext={true} makes my customfilter opened at different location instead of clicked button

**Expected behavior**
The filter dialog should be opened exactly below the filter icon on the column header

**Minimal reproduction of the problem with instructions**
set reactNext={true} and try to set custom filter component for some column and see the issue

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-react version:** 2.0.X
ag-grid-community ^21.0.1

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
ag-grid-community ^21.0.1

* **React version:** 2.0.X
16.9.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Es6

**Comment by seanlandsman** [comment]
Hi

Issue AG-3458 has been raised for this - you can track it's progress in our pipeline here:  https://www.ag-grid.com/ag-grid-pipeline/
