### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by tiagoefmoraes** [ag-grid/ag-grid-react#39]
Couldn't find any information on this so I'm asking here.
Why is `AgGridReact` defined only as `any`?

``` typescript
export declare var AgGridReact: any;
```

Is there any work being done to properly type it?

**Comment by ceolter** [comment]
because we declare the class using the React.createClass method:

export var AgGridReact = React.createClass({

**Comment by tiagoefmoraes** [comment]
`React.createClass` returns `ClassicComponentClass<P>`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react/index.d.ts#L102

react-router also defines the Router class as 
```typescript
const Router = React.createClass({
```
https://github.com/ReactTraining/react-router/blob/master/modules/Router.js#L31

and the type is defined as 
```typescript
interface Router extends React.ComponentClass<Router.RouterProps> { }
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react-router/lib/Router.d.ts#L9

Defining it as `any` allows full use but gives no typing benefits (suggestions / type verifications)

Typings for AgGridReact could be enhanced if properly defined.

I started typing it in my project (**very limited API usage**) and its looking like this:

```typescript
import React from "react";
import { ColDef } from "ag-grid";

declare module "ag-grid-react" {
  interface Props {
    columnDefs: Array<ColDef>;
    enableColResize: boolean;
    enableServerSideSorting: boolean;
    headerHeight: number;
    onSelectionChanged: () => void;
    onSortChanged: () => void;
    rowHeight: number;
    rowModelType: "virtual";
    rowSelection: "single";
    suppressMovableColumns: boolean;
    suppressMultiSort: boolean;
    suppressNoRowsOverlay: boolean;
    suppressCellSelection: boolean;
    onRowDoubleClicked: () => void;
  }

  export class AgGridReact extends React.Component<Props, {}> {
  }
}
```

It's a lot of work but gives me the full benefits of types...

**Comment by ceolter** [comment]
is it just the props you are after? how about using GridOptions?

```
import {GridOptions} from 'ag-grid/main';
```

**Comment by ceolter** [comment]
can you explain, how you would use this? i thought React puts the options one by one into the HTML template - so how would you use an interface?

**Comment by tiagoefmoraes** [comment]
GridOptions helps a lot, changed my code to this:
```typescript
  interface Props extends GridOptions {
  }

  export class AgGridReact extends React.Component<Props, {}> {
  }
```

I use like this:
```typescript
  render() {
    return (
      <AgGridReact
        ...
        rowModelType="virtual"
        onRowDoubleClicked={this.props.rowDoubleClicked}
        headerHeight={32}
        rowHeight={32}
        // Than if I try to use wrong property or mistype the compiler gives me errors:
        //[ts] Property 'wrongProperty' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<AgGridReact> & Props & { children?: {} | undefined...'.
        wrongProperty="value"
        />
    );
  }
```
and if I type the properties more strictly like `rowModelType: "virtual" | "normal";` instead of `rowModelType: string;` I get compile time errors for wrong values too:
```typescript
//[ts] Type '"special"' is not assignable to type '"virtual" | "normal"'.
rowModelType="special"
```

**Comment by tylermassey** [comment]
+1 for this

I'm new to `ag-grid`, but it looks like developers have to either use `GridOptions` or the props on `AgGridReact`.

I bet many React devs prefer using the props on `AgGridReact`. And if the consuming devs are using TypeScript, it is a huge benefit to have compile-time type checking on those props.

**Comment by seanlandsman** [comment]
This seems like a reasonable request - I've raised issue AG-598 for this and will try get it in for the next release, but the release after at the latest

I'll update this thread with updates as soon as I have any

**Comment by seanlandsman** [comment]
@tiagoefmoraes I'm finally getting around to incorporating this

Are you able to share your tsc/webpack etc config? It would be useful to have a baseline to use to test the changes

thanks

**Comment by seanlandsman** [comment]
This work is now complete - if you're interested take a look at the latest branch :-)

**Comment by mellis481** [comment]
@seanlandsman My understanding from reading (skimming) over this thread is that people were requesting TypeScript typings for AgGrid and your last update made me believe that this was completed last August.  I'm not seeing any typings when I install the latest ag-grid-react NPM dependency.  Please advise.
