### ISSUE TITLE
`setFocusedCell` is not working for `cellEditorFramework`

### ISSUE THREAD

**Issue by ralphsmith80** [ag-grid/ag-grid-react#57]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

1. Render ag-grid
2. Make row editable
3. Set focus on first cell

**Expected behavior**

Instantiate the grid invoke start editing and cursor is placed in the first cell so I can start typing.

**Minimal reproduction of the problem with instructions**

```
columns = [
  {
    colId: 'name',
    headerName: 'name',
    field: 'name',
    headerTooltip: 'Name',
    tooltipField: 'name',
    editable: true,
    cellEditorFramework: NameCellEditor,
  },
]
...
onGridReady={(params) => {
  params.api.sizeColumnsToFit()
  params.api.startEditingCell({
    rowIndex: 0,
    colKey: 'name',
  })
  params.api.setFocusedCell(0, 'name')
  // this is my current workaround
  // let firstRow = params.api.rowRenderer.renderedRows[0]
  // firstRow.renderedCells.name.setFocusInOnEditor()
}} />
```

**What is the motivation / use case for changing the behavior?**

Using ag-grid editable feature for data entry grid.

**Please tell us about your environment:**

Mac OSX Sierra

* **ag-grid-react version:** 2.0.X

version: 8.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **React version:** 2.0.X

react version: 15.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 56.0.2924.87 (64-bit)
Developer FireFox 53.0a2 (2017-02-14) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by seanlandsman** [comment]
Hi

I've just tried this with out editor examples (https://github.com/ag-grid/ag-grid-react-example/tree/master/src/editorComponentExample) 

Adding the following:

```        this.gridApi.startEditingCell({
            rowIndex: 0,
            colKey: 'number',
        });
```
to EditorComponentsExample's onGridReady starts editing in that cell, with focus already set

If you can provide an example of this not working for you I'll be happy to take a look

thanks

**Comment by fireappsAdmin** [comment]
I'm having the same issue but it only loses focus when there are more than 27 rows. 26 rows and less and there seems to be no problem.
