### ISSUE TITLE
Unable to suppress navigation events in ag grid react without suppressing react events in editor component

### ISSUE THREAD

**Issue by seanlandsman** [ag-grid/ag-grid-react#60]
Moved from https://github.com/ceolter/ag-grid/issues/1527

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A similar feature request to this has already been raised https://github.com/ceolter/ag-grid/issues/921.

However, the proposed solution (using event.stopPropagation) doesn't work with the react version of the ag grid. This is because react implements a global event handler and dispatches synthetic events to its components. https://github.com/facebook/react/issues/8693

Since ag grid is not a react component and isn't driven by react events, I cannot stop propagation within a react event handler; I have to implement a dom event handler and stop propagation within it. This stops the event from reaching any react components, regardless of weather they are children or parents of the component which stops the propagation.

**Expected behavior**

Ideally, it should be possible to turn off navigation keys for editors through a flag on the column definition. 

```
columnDefs: {
        {headerName: 'Col A', field: 'a', cellEditorFramework: MyReactComponent, suppressNavigationInEditMode: true }
    }

```

I understand that this solution is extremely coupled to the problem. However,  given the way react works and the fact that ag grid is not driven through react events, I can't see another solution. I'll be implementing this in a fork, so if you want I can submit a PR.

**Minimal reproduction of the problem with instructions**
This plunkr shows an example of the issue http://plnkr.co/edit/Cdz9yqI7k9qgoGQc2u2a?p=preview

Stopping dom event propogation in TestEditor doesn't block the dom event in TestEditorSubComponent, but it blocks the react event from reaching that same component. Therefore there is no way for me to stop navigation keydown events from reaching Ag Grid while at the same time handling those same events within my component. Doing everything through dom events is not an option, as I can't use third party react components in that case.

* **ag-Grid version:** 8.2.0
* **ag-Grid-React version:** 8.2.0

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

* **Language:** [TypeScript 2.2.1 | ES7 ]

@rrhvella

**Comment by seanlandsman** [comment]
@rrhvella

**Comment by billyvg** [comment]
Are there currently any workarounds for this?

**Comment by rrhvella** [comment]
I don't think there's a workaround. We're maintaining a fork at work to fix this problem: https://github.com/MySchoolManagement/ag-grid/tree/feature/suppress-cell-navigation

The fork is for ag-grid, not ag-grid-react.

Please note that I still have to update it to version 9 though.

**Comment by vespaiach** [comment]
In your ag-grid editor component, you can listen for 'keydown' event and stop propagation on navigation keyboard

```
class EditorComponent extends Component {
  componentDidMount() {
      this.input.addEventListener('keydown', this.stopNavigation);
  }

  componentWillUnmount() {
      this.input.removeEventListener('keydown', this.stopNavigation);
  }

  stopNavigation(event) {
    if ([32, 37, 38, 39, 40, 36, 35].indexOf(event.keyCode) > -1) {
      event.stopPropagation();
    }
  }

  render() {
    return <input ref={(input) => { this.input = input; }}/>
  }
  .....

```

**Comment by seanlandsman** [comment]
thanks @vespaiach 

Sorry for the delay @rrhvella - I've updated our mood editor to illustrate how you can do what you're after: https://github.com/ag-grid/ag-grid-react-example/blob/latest/src/editorComponentExample/MoodEditor.jsx

thanks

**Comment by rrhvella** [comment]
@seanlandsman 
I'm actually sorry for not answering this earlier. This solution doesn't actually help, as I said in my original post:

"Stopping dom event propogation in TestEditor doesn't block the dom event in TestEditorSubComponent, but it blocks the react event from reaching that same component. Therefore there is no way for me to stop navigation keydown events from reaching Ag Grid while at the same time handling those same events within my component. Doing everything through dom events is not an option, as I can't use third party react components in that case."

**Comment by aodinok** [comment]
We have exactly the same issue with passing keyboard events to the 3rd party React editor (DatePicker) like @rrhvella explaining. 2 years passed and still no fix for this? How about to reopen this issue, I'm happy to contribute.

**Comment by svanetten1976** [comment]
I'm having this same exact problem and its driving me absolutely nuts. I have a custom cell editor (cellRendererFramework) that listens for keydown and used to block the arrow keys from navigating the grid with event.stopPropagation. That no longer works, at least as of ag-grid 20 and the introduction of suppressKeyboardEvent. And if I try to block navigation in that callback, the cursor won't move in my custom input:

`suppressKeyboardEvent = params => {
    const { isEditing } = this.props

    const component =
      params.colDef &&
      params.colDef.cellRendererFramework &&
      params.colDef.cellRendererFramework.WrappedComponent &&
      params.colDef.cellRendererFramework.WrappedComponent.name
        ? params.colDef.cellRendererFramework.WrappedComponent.name
        : ''
    const event = params.event
    const key = event.which
    const arrowKeys = [37, 39]
    if (isEditing && arrowKeys.includes(key) && component) {
      console.log('suppress', params)
      return true
    }
    
   return false
  }`
