### ISSUE TITLE
Ag-grid loses selection state when rows get updated

### ISSUE THREAD

**Issue by pupeno** [ag-grid/ag-grid-react#68]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the property containing the rows gets updated, for example, by adding a row, all rows lose the selection status immediately becoming unselected. 

**Expected behavior**
The previously selected rows should remain selected and if all rows are selected, the new rows should also be selected. 

**Minimal reproduction of the problem with instructions**
Create a grid with any sort of selection (single, multiple, checkbox) where the rowData is coming form a property, load some data into that property, select some rows, load some more data. Observe now now row is selected. 

**What is the motivation / use case for changing the behavior?**
Just to have a stable selection of rows. 

**Please tell us about your environment:**
Windows, ag-grid, ag-grid react from the ClojureScript packages we built. ClojureScript, Windows, etc. 

* **ag-grid-react version:** 9.1.0
* **React version:** 15.4.2
* **Reagent version:** 0.6.2
* **Browser:** Chrome 53.0.2785.116
* **Language:** ClojureScript 1.9.89

**Comment by seanlandsman** [comment]
Hi,

There are now a variety of new ways to update (add, remove and modify) that will maintain grid state.

Please refer to http://www.ag-grid.com/javascript-grid-data-update/?framework=react for more information

**Comment by bondib** [comment]
This issue still exists (ag-grid version 14.2.0) - when using the new tree data model.
State isn't preserved when using api.updateRowData(transaction) (and other methods as well).

**Comment by DominicTobias** [comment]
> Hi,
> 
> There are now a variety of new ways to update (add, remove and modify) that will maintain grid state.
> 
> Please refer to http://www.ag-grid.com/javascript-grid-data-update/?framework=react for more information

We've been suffering for a year with no idea about this `deltaRowDataMode` option :o Fixes some nasty hacks we had to put in place to reselect the rows etc and seems more performant
