### ISSUE TITLE
Complex to use ag-grid as a form input mechanism with responsive field validation 

### ISSUE THREAD

**Issue by ralphsmith80** [ag-grid/ag-grid-react#71]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using ag-grid as a form input mechanic. The idea is to collect a list of models that will be posted to the server for creation. Within each row each field is a custom field, specifically a [material-ui textField](http://www.material-ui.com/#/components/text-field) component. As you would expect with typical forms I'm providing responsive validation for each field and form level validation to enable/disable the submit button.

I've got this mostly working with much effort, but there's a few things still lacking overall due to the way ag-grid plays with the React lifecycle when the grid is editable. 

The basics is that every time I update the parent form component for validation it triggers a render on the child grid which toggles the grid back into read-only mode. I have to keep track of the field that was being edited so I can programmatically re-enable editing and set focus on the correct field. Messy and it flickers a bit but 95% there. 

Next I had to override arrow key navigation so I could move within the input to allow editing the content not just delete and append as you type. Basic html input behavior. However, once I change the value the whole validation process is repeated with changed values and the cursor position is set back to the end of the input. At this point I could also keep track of cursor position and programmatically set that after setting field focus, but this is starting to feel very wrong.

**Expected behavior**
Use editable ag-grid as a form input with responsive field validation.

**Minimal reproduction of the problem with instructions**

1. Create an form
2. Add ag-grid as an input component
3. Use a custom input field for column
4. Provide field validation for custom input field
  a. e.g. ip field that validates if input is an ip address as the user types
5. Provide form validation
  a. the submit button is only enabled once the user has entered a valid IP address in the ip field
6. After a value has been entered in the IP field the user uses the arrow keys to edit the middle part of the address.

Just to note I'm doing this the react way with an errorText prop that is set on the text field. Doing this another way that is not react idiomatic might work, but since I'm using the react version of ag-grid I expect this to be idiomatic.

* **ag-grid-react version:** 2.0.X
"ag-grid": "8.0.0"
"ag-grid-react": "8.0.0"

* **React version:** 2.0.X
"react": "15.5.4"

* **Browser:** 
Chrome 58.0.3029.110

**Comment by seanlandsman** [comment]
Hi,

We've made a number of changes in the last two releases of ag-grid (and ag-grid-react) around this area, specifically around data updates (https://www.ag-grid.com/javascript-grid-tree/?framework=react) and property change detection on the react side of things

I'd suggest you see if these improvements help you - if not, can you perhaps provide an example of what you're seeing? With something to look and and use as a baseline we can see how/if we can add support for what you're after

thanks
