### ISSUE TITLE
AgGrid doesn't refresh when columns change

### ISSUE THREAD

**Issue by pupeno** [ag-grid/ag-grid-react#72]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Where the columnDefs is property that changes, because shouldComponentUpdate always returns false, columns don't get updated when they change. 

**Expected behavior**
When the columns get updated, the grid should refresh. 

**Please tell us about your environment:**
* **ag-grid-react version:** 10.0.0
* **React version:** 15.4.2

* **Browser:** Chrome 53.0.2785.116
* **Language:** ClojureScript

**Comment by seanlandsman** [comment]
Hi

I cant reproduce this. If I bind columnDefs to something like this.state.columnDefs and change the state to say add a new column, the grid updates

Do you have a reproducible example I can take a look at?

**Comment by seanlandsman** [comment]
Closed due to inactivity
