### ISSUE TITLE
Request: React component for group cell renderer

### ISSUE THREAD

**Issue by tylermassey** [ag-grid/ag-grid-react#76]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
To customize group cells, one needs to use an `ag-grid` cell renderer like in the example [here](https://ag-grid.com/javascript-grid-cell-rendering/#gsc.tab=0) and below.

```
colDef = {
    // tell the grid we want to show group values in this column
    showRowGroup: true,
    // set the cell renderer to 'group'
    cellRenderer: 'group',
    // provide extra params to the cellRenderer
    cellRendererParams: {
        suppressCount: false, // turn off the row count
        checkbox: true, // enable checkbox selection
        padding: 10, // set padding to 10px
------> innerRenderer: myInnerRenderer, // provide an inner renderer
        footerValueGetter: myFooterValueGetter // provide a footer value getter
    }
    ...
};
```

**Expected behavior**
Having an `innerRendererFramework` option for a React component.

**What is the motivation / use case for changing the behavior?**
`ag-grid-react` allows using React components instead of `ag-grid` renderers in many other location but not in this case. It is a more pleasant experience to work only with React components instead of mixing `ag-grid` renderers with React components.

**Please tell us about your environment:**

* **ag-grid-react version:** 11.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 11.0.0

* **React version:** 15.4.1

* **Language:** TypeScript

**Comment by seanlandsman** [comment]
Hi

There is already an open issue for this our side (AG-253) - its marked as high priority so should be available soon

We'll update this thread with updates as soon as we have any

thanks

**Comment by rodoabad** [comment]
@seanlandsman anyway that issue can be made visible to the public? Or at least an ETA? Thanks!

**Comment by lauracurley** [comment]
ETA would be great.

**Comment by makinggoodsoftware** [comment]
Hi,

We just finished coding this, it will be in the next release ETA 2/3 weeks

**Comment by seanlandsman** [comment]
This has been done - available in 13.x onwards

**Comment by DominicTobias** [comment]
Is there any way to drive that checkbox value from row data?
