### ISSUE TITLE
Accessing factories like React.DOM.div has been deprecated

### ISSUE THREAD

**Issue by ido-ofir** [ag-grid/ag-grid-react#82]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

with React >= 15.6.0 a warning appears in the console:
![image](https://user-images.githubusercontent.com/6238323/29078891-4d0ef396-7c64-11e7-8697-eb38bab71659.png)

**Expected behavior**

use react-dom-factories to remove the warning
**Minimal reproduction of the problem with instructions**

start a project with React >= 15.6.0 and try to use the component

**What is the motivation / use case for changing the behavior?**

in master/src/agGridReact.ts:
![image](https://user-images.githubusercontent.com/6238323/29079999-59740e3e-7c67-11e7-98f9-4636bd872f75.png)

change 'React.DOM' to use [react-dom-factories](https://www.npmjs.com/package/react-dom-factories)

**Please tell us about your environment:**

on MacOS, using webpack.
* **ag-grid-react version:** 12.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 12.0.0

* **React version:** 15.6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by seanlandsman** [comment]
Hi

This has been done - these warning will no longer appear in our next release.

thanks
