### ISSUE TITLE
ag-grid - Getting blank space after the last column on resizing the other columns

### ISSUE THREAD

**Issue by NanPriTK** [ag-grid/ag-grid-react#83]
Hi, I am using ag-grid to display certain details for my application. I used gridOptions.api.sizeColumnsToFit() to get equal width for all columns. When I resized any of the columns i  am getting empty space after the last column in the grid. How to make the last column takes the extra blank space on resizing the previous columns. Below I attached the sample of my application
1. grid sample before column resize
![beforeresize](https://user-images.githubusercontent.com/22371944/29456451-4cd54bce-8433-11e7-9f60-5281eeb2c6c1.PNG)
2. After resizing column Year in the grid
![afterresizeyearcolumn](https://user-images.githubusercontent.com/22371944/29456482-66e6cee8-8433-11e7-9678-947de3800638.PNG)

In this case I need to avoid the blank space after column- Country and maintain the updated column size for Year. Is it possible to apply sizeColumnsToFit() only for column -Country
can anyone suggest how to handle this situation.

**Comment by seanlandsman** [comment]
As per the issue template, please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

You can use the gridSizeChanged event and then call sizeColumnsToFit on change. Alternatively take a look at our responsiveness docs here for other options: https://www.ag-grid.com/javascript-grid-responsiveness/
