### ISSUE TITLE
Keyboard event preventing grid from editing

### ISSUE THREAD

**Issue by bwqdxxg** [ag-grid/ag-grid-react#85]
The sample in the mood editor is invalid
There is no event.stopPropagation ();

`
componentDidMount(){
    document.addEventListener('keydown', this.checkAndToggleMoodIfLeftRight);
}
checkAndToggleMoodIfLeftRight=(e)=>{
    e.stopPropagation();
}
`

**Comment by seanlandsman** [comment]
I'm afraid I cant see what you're referencing - this appears to work in both chrome and firefox (I've not tried IE)

If you can provide more information I'd be happy to investigate
