### ISSUE TITLE
ag-grid-react 13.0.0 broken Drag and Drop of columns

### ISSUE THREAD

**Issue by cmelgarejo** [ag-grid/ag-grid-react#86]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting => not found.
```

**Current behavior**
When you try to drag and drop any column form the grid or the toolPanel you get an error message in the console:

Chrome 60:
```
 DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at DragAndDropService.createGhost

react-examples.js:56589 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at DragAndDropService.createGhost (http://localhost:8080/dist/react-examples.js:56589:32)
    at DragAndDropService.onDragStart (http://localhost:8080/dist/react-examples.js:56428:15)
    at DragService.onCommonMove (http://localhost:8080/dist/react-examples.js:43656:41)
    at DragService.onMouseMove (http://localhost:8080/dist/react-examples.js:43677:15)
```

Firefox 54.0.1:
```
SyntaxError: An invalid or illegal string was specified  react-examples.js:56589
	DragAndDropService</DragAndDropService.prototype.createGhost http://localhost:8080/dist/react-examples.js:56589:10
	DragAndDropService</DragAndDropService.prototype.onDragStart http://localhost:8080/dist/react-examples.js:56428:10

	DragService</DragService.prototype.onCommonMove http://localhost:8080/dist/react-examples.js:43656:18
	DragService</DragService.prototype.onMouseMove http://localhost:8080/dist/react-examples.js:43677:10

TypeError: this.eGhostIcon is undefined[Saber más] react-examples.js:56642:10
	DragAndDropService</DragAndDropService.prototype.setGhostIcon http://localhost:8080/dist/react-examples.js:56642:10
	DragAndDropService</DragAndDropService.prototype.enterDragTargetIfExists http://localhost:8080/dist/react-examples.js:56465:10
	DragAndDropService</DragAndDropService.prototype.onDragging http://localhost:8080/dist/react-examples.js:56451:14

	DragService</DragService.prototype.onCommonMove http://localhost:8080/dist/react-examples.js:43660:10
	DragService</DragService.prototype.onMouseMove http://localhost:8080/dist/react-examples.js:43677:10
```
**Expected behavior**
To be able to drag and drop columns into the grouping space in pivot mode or the toolPanel for aggregation, as always there should be a "Ghost" version of the header you are dragging but that's exactly what's failing right now.

**Minimal reproduction of the problem with instructions**
cloning **ag-grid-react-example** repo and use the `npm run examples` command and navigate to `http://localhost:8080/` as per usual instructions in the `README.md` file of the https://github.com/ag-grid/ag-grid-react-example project

**Please tell us about your environment:**

Windows 10 Pro, Visual Studio Code, Webpack

* **ag-grid-react version:** 13.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 13.0.0

* **React version:** 15.6.1

* **Browser:** Chrome 60.0.3112.101 | Firefox 54.0.1

* **Language:** ES6/7

**Comment by cmelgarejo** [comment]
Also the examples for React are broken in the ag-grid.com site :(

**Comment by tewksbum** [comment]
+1

**Comment by seanlandsman** [comment]
Hi - taking a look at this now

**Comment by seanlandsman** [comment]
@cmelgarejo what part of the example is broken?

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-710 our side to track this 

It'll be fixed today and be included as part of a patch release due later today, or first thing tomorrow

thanks

**Comment by petyosi** [comment]
The issue should be fixed in 13.0.1, about to be released today.

**Comment by cmelgarejo** [comment]
Is v13.0.1 going to be published on npmjs?
thanks!

**Comment by seanlandsman** [comment]
That should happen automatically - thanks
