### ISSUE TITLE
TypeScript types for ag-grid-react 13 broken!!

### ISSUE THREAD

**Issue by amirburbea** [ag-grid/ag-grid-react#87]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
agGridReact.d.ts seems to think the AgGridReact component has props that simply extend GridOptions.

This is not true.  The props object has a property named `gridOptions` which takes a GridOptions object.

**Expected behavior**

Using the control should be as simple as 

```ts
<AgGridReact gridOptions={gridOptions} />
```

but now instead I need to do the following

```ts
const AgGrid: any = AgGridReact;
return (<AgGrid gridOptions={gridOptions} />);
```

* **ag-grid-react version:** 13.0

* **ag-Grid/ag-Grid-Enterprise version:** 13.0

* **React version:** 15.6.1

* **Browser:** [all ]

* **Language:** TypeScript 2.4.2

**Comment by cmelgarejo** [comment]
Is the column dragging (check in https://www.ag-grid.com/example-react-rich-grid/#gsc.tab=0 "show tool panel" and drag columns to the group//order areas) broken for you too? If it is, please 👍 this issue: https://github.com/ag-grid/ag-grid-react/issues/86

**Comment by seanlandsman** [comment]
Hi - this was an oversight, I'll add gridOptions to it today

**Comment by seanlandsman** [comment]
This has now been fixed - it'll be available in our next release, due out today or first thing tomorrow

**Comment by amirburbea** [comment]
Just saw the check in. I would say it's not right (though it will work) as props does/should not extend GridOptions. 

I also had tried

```ts
<AgGridReact {...gridOptions} />
```

And it never worked right
