### ISSUE TITLE
stopEditing() api does not work

### ISSUE THREAD

**Issue by tmpg** [ag-grid/ag-grid-react#90]
[x ] bug report

Current behavior
Tried using stopEditing() API to programmatically exit the editor. It doesn't work.

Expected behavior
Calling the stopEditing() API forces the editor to exit editing mode.

Minimal reproduction of the problem with instructions
Enter a cell and start editing.
Call: this.gridApi.stopEditing() or this.gridApit.stopEditing(true);
Nothing happends.

What is the motivation / use case for changing the behavior?
stopEditing() API to programmatically exit the editor

Please tell us about your environment:
All

ag-Grid version: X.X.X
13.0.1 popup editor material-theme

Browser:
Chrome

Language:
Reactjs

**Comment by seanlandsman** [comment]
Hi - I cant reproduce this on our example here https://www.ag-grid.com/example.php or in our react examples

If you can provide a repro of this I'll be happy to take a look

thanks
