### ISSUE TITLE
deltaRowDataMode not compatible with doesDataFlower  

### ISSUE THREAD

**Issue by jmoore315** [ag-grid/ag-grid-react#92]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Setting deltaRowDataMode={true} in AgGridReact breaks row flowering via doesDataFlower. 

**Expected behavior**
Should be able to use deltaRowDataMode and row flowering

**Minimal reproduction of the problem with instructions**

Please see the following webpack bin: https://www.webpackbin.com/bins/-KtJTSxqmH1GBnPanT5D 
Edit line 72 to view the bug in action

**What is the motivation / use case for changing the behavior?**
This is a bug

**Please tell us about your environment:**

* **ag-grid-react version:** 2.0.X
13.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X
13.0.0

* **React version:** 2.0.X
15.6.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-745 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
This should work now

**Comment by jmoore315** [comment]
Confirmed this is working now, thanks!
