### ISSUE TITLE
rememberGroupStateWhenNewData does not work with flowered rows

### ISSUE THREAD

**Issue by jmoore315** [ag-grid/ag-grid-react#94]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
rememberGroupStateWhenNewData does not work for flowered rows. Setting new rowData with       `rememberGroupStateWhenNewData={true}` still results in the grid collapsing all groups (expanded flower rows). 

**Expected behavior**
Setting rowData should keep groups expanded if rememberGroupStateWhenNewData = true

**Minimal reproduction of the problem with instructions**
Webpack bin: https://www.webpackbin.com/bins/-KtTb-XheXx7s2MnvF2O 
Altering rowData by adding top level data (Add Item button) or nested data (Add Bid) button causes expanded rows to be collapsed. 

**What is the motivation / use case for changing the behavior?**
Bug

**Please tell us about your environment:**
OSX / yarn / node v6.11.2

* **ag-grid-react version:**: 13.1

* **ag-Grid/ag-Grid-Enterprise version:** 13.1
* **React version:** 15.5.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that this only supported as part of the grouping feature available on the enterprise version of ag-grid.

You will have to expand collapse the nodes manually or set the data on them directly yourself I am afraid

**Comment by jmoore315** [comment]
I am on the enterprise version, it still does not work

**Comment by jmoore315** [comment]
@makinggoodsoftware could you reopen this issue & investigate using enterprise? Thanks!
