### ISSUE TITLE
`deltaRowDataMode` breaks cell updates under certain conditions

### ISSUE THREAD

**Issue by grovesNL** [ag-grid/ag-grid-react#98]
I forked the [Redux plunkr](https://www.ag-grid.com/example-react-redux/) to create an example of a controlled input (a checkbox). The checkbox is driven by the `toggle` state in a Redux store.

My plunkr can be found at https://plnkr.co/edit/r8WeWexCmmwDPvNmoe9y?p=preview

The idea is that my checkbox is toggled by dispatching an action, which in turn updates the store with the new toggle status. The new toggle status is passed down to ag-grid but the cell never rerenders. As a result, the user isn't able to toggle this state.

If you remove the `deltaRowDataMode` then this checkbox behaves as expected.

I also looked into how the row delta was being calculated, and it seems to appear correctly in the transaction as an update. However the cell is never actually rerendered with the new value. It's not obvious where it stops.

As a side note, there are ways to trigger the refresh to occur afterwards by performing certain actions. If the input was instead exposed with `cellEditorFramework` (i.e. `cellRendererFramework` just displays a text value), after editing is complete, the value displayed will be the prior value. However, entering and exiting edit mode again will trigger the new value to be displayed.

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-react/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Certain cells don't rerender when `deltaRowDataMode` is enabled, even when the delta should include them.

**Expected behavior**
The delta rerenders the cell with the updated value.

**Minimal reproduction of the problem with instructions**
Run my plunkr and try to toggle the checkbox. Notice that the checkbox cannot toggle. Remove `deltaRowDataMode` and try to toggle the checkbox. Notice that the checkbox toggles fine.

**What is the motivation / use case for changing the behavior?**
Controlled inputs should be supported with `deltaRowDataMode`.

* **ag-grid-react version:** 13.1/latest

* **ag-Grid/ag-Grid-Enterprise version:** 13.1/latest

* **React version:** latest

* **Browser:** Chrome

* **Language:** TypeScript

**Comment by grovesNL** [comment]
There was a bug in my original example - I've just updated at https://plnkr.co/edit/r8WeWexCmmwDPvNmoe9y?p=preview

**Comment by grovesNL** [comment]
If there is anything I can do to help further or a way to work around this, please let me know. It feels like there is just a missing re-render call for the cell somewhere. This issue is important to me because each  of my grids are bound directly to Redux state and controlled like the example.

The previous workaround I've used is to deep clone all Redux state that the grid depends on (so that ag-grid can mutate it directly without altering the data in the store). However the performance hit from that solution is too great, and the grid becomes unusable for edits.

**Comment by seanlandsman** [comment]
@grovesNL Hi - I was taking a look at this but I'm afraid neither of the plunkers above run correctly. Can you please take a look and correct the issue?  

thanks

**Comment by grovesNL** [comment]
@seanlandsman Thanks for taking a look. What happens for you when you run the plunkers? They run fine for me on Chrome and Edge.

To reproduce:

- Attempt to toggle any checkbox in the `Toggle` column
  - Note that the store has updated, but the checkbox continues to render the stale state (which makes it seem as though the toggle failed)
- Remove `deltaRowDataMode` from `GridComponent.jsx`
- Attempt to toggle any checkbox
  - Note that the store and checkbox both update

**Comment by seanlandsman** [comment]
Hi

My bad, I saw an error when I grouped - AND I hadnt scrolled to the right to see the checkbox

I've taken a loo and the issue here is that you need to specify the field to use in the colDef - once I added this it works as expected

I've forked it here with the fix (also has a bit more noise as I was adding/removing things while I investigated): https://plnkr.co/edit/7OzP4WBDBCyAY8xORIaI?p=info

thanks

**Comment by grovesNL** [comment]
@seanlandsman Thanks! Unfortunately I can’t specify a `field` for the majority of my column definitions. The columns all use custom renderers and editors which depend on more than just one property. That’s why I’m wondering whether the cell could refresh regardless in this case, this sounds like an optimization to avoid a refresh (which is only relevant applies if `field` is used). Shouldn’t it behave the same way whether `deltaRowDataMode` is enabled or not?

**Comment by grovesNL** [comment]
Any ideas? I'm using a workaround at the moment but I would be surprised if other people don't hit this issue.

**Comment by fabioDMFerreira** [comment]
@seanlandsman I have forked your plunkr and replaced "toggle raw" cell renderer by a custom component. Now if we click on toggle the "toggle raw" cell isn't updated.

https://plnkr.co/edit/7OzP4WBDBCyAY8xORIaI?p=preview

@grovesNL Did you find a solution to this problem?
