### ISSUE TITLE
PivotMode Not Working Properly

### ISSUE THREAD

**Issue by JimTheMan** [ag-grid/ag-grid-react#99]
(sorry for double posting this on ag-grid lirbary also, but I found this project later and realised it's probably more appropriate for my issue)

I'm submitting a ... (check one with "x")

[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
Current behavior

When I set "pivotMode" on the React AgGrid it does not show data properly.

For some reason Github won't let me upload images here, but with "pivotMode" turned on my grid had one single column that says, "sum(Metric)" with a value "la(1)". There is also no column with a header "Groups" which is something that I wanted.

It is very confusing to use this grid in a React project because there are literally ZERO examples in the docs that actually make use of the tag!

Expected behavior

I want the left header to say "Groups" with the label names under them, and a column labeled "Nums" with a cell under it showing the sum of nums with that label. I'm trying to use these arrays for the columns and rows:

columns: [
      {headerName: "Metric", field: "metric", width: 100},
      {headerName: "Currency", field: "currency", width: 120},
      {headerName: "discriminator", field: "discriminator"},
      {headerName: "label", field: "Label", minWidth: 50, width: 100, rowGroup: true, columnGroupShow:"open"},
      {headerName: "Nums", field: "numOfThings", width: 100, value:true, aggFunc:"sum"}
    ]

    rows: [{
      "numOfThings": 1,
      "discriminator": "foo",
      "Label": "la",
      "metric": "20",
      "currency": "EUR"
    }
Here how I am creating the grid:

<AgGridReact className={"grid-container"}
         columnDefs={this.props.columns}
         rowData={this.props.rows}
         groupUseEntireRow
         enableColResize
         pivotMode
         onSelectionChanged={this.onSelectionChanged}
         onCellClicked={this.onCellClicked}
         onClick={this.onCellClicked}
         onGridReady={this.onGridReady}>
       </AgGridReact>
It looks normal when I take off pivotMode.

Minimal reproduction of the problem with instructions

What is the motivation / use case for changing the behavior?

Please tell us about your environment:

ag-Grid version: 13.2.0
Browser: Chrome
Language:  ES6

**Comment by makinggoodsoftware** [comment]
Hi,

Not sure why you think this is a bug, this is how pivot is designed to work....
